version: '3.8'
name: "deck1090-dev"


networks:
  devcontainer:

services:
  app:
    image: "mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm"
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks: ["devcontainer"]

  db:
    image: "timescale/timescaledb:latest-pg16"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data # only for non-HA image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    networks: ["devcontainer"]

  redis:
    image: "bitnami/redis:latest"
    volumes:
      - redis-data:/bitnami/redis/data
    networks: ["devcontainer"]

volumes:
  postgres-data:
  redis-data: